### ISSUE TITLE
Testen UDP Server

### ISSUE THREAD

**Issue by MoritzGerlach** [RubenHaag/Projekt-X#11]
Testen ob der UDP Server mit drei Clients geht.

- [x] ein Client
- [x] zwei Clients
- [x] drei Clients

**Ziel muss sein bis Sonntag den test erfolgreich abgeschossen zuhaben (Den test mit drei Clients).**

**Comment by MoritzGerlach** [comment]
Tag  @OskarHowe @RubenHaag 
**Ich habe ein Problem**. Ich kann nicht mit drei Clients testen. Da jeder Client sich an den Selben Port bindet muss, dass geht aber nicht auf einem PC. Ich habe aber nicht die Möglichkeit das mit drei PCs zu testen.

**Comment by RubenHaag** [comment]
Nimm noch den Raspberry pi dazu

**Comment by RubenHaag** [comment]
Sonst kann ich dir auch meine Ip morgen mal schicken

**Comment by MoritzGerlach** [comment]
**Danke @RubenHaag!**
An den Raspberry pi habe ich noch nicht gedacht. Ich versuche es erstmal mit dem bei Raspberry pi und einen anderen PC.

**Comment by MoritzGerlach** [comment]
**Das Problem bei dem Testen. (Test mit zwei clients)**
Entweder der Code ist falsch, dann finde ich den Fehler nicht, da ich eigentlich alles schon mal einzel geprüft habe oder das Problem ist, dass die Firewall oder das Virenschutzprogramm, auf einen der beiden PCs, die Pakete abfängt.
Kannst du dir es mal anlesen und schauen, ob da ein Fehler ist.
@RubenHaag @OskarHowe

**Comment by MoritzGerlach** [comment]
# Test mit mehreren Clients. 
## 2 Clients: erfolgreich.

- Server erhält Daten vom jedem Client
- Server kann Daten versenden
- Client empfängt Daten
- Client kann Daten versenden

**Aber es ist erforderlich, die Firewall zu deaktivieren.** 
Wir können uns überlegen, die Clients und den Server über eine Local Area Network (LAN) zu verbinden. Dann könnten wir, die Firewall deaktivieren.
Wir benötigen hat nur 3 oder 4 Laptops (drei Clients und einen Server) und LAN-Kabels oder einen Hot Spot vom Handy. 
@OskarHowe
