### ISSUE TITLE
Java-Dokumentation

### ISSUE THREAD

**Issue by MoritzGerlach** [RubenHaag/Projekt-X#12]
Java-Dokumentation für den Server und Client

- [x] UDP Server
- [x] UDP Client
- [x] TCP Server
- [x] TCP Client
- [x] Die zusammen gefaste Version: Server
- [x] Die zusammen gefaste Version: Client

**Comment by MoritzGerlach** [comment]
Tag @RubenHaag 
Kannst du dir mal den UDP-Server und den UDP-Client anschauen und sagen was für die Java-Dokumentation **noch fehlt** oder **nicht richtiggemacht wurde**. Danke

**Comment by RubenHaag** [comment]
Bei dem Client Fehlt noch die Dokumentation der Client Klasse, also der Kommentar obendrüber
Ansonsten dürfen die Beschreibungen gerne auch ausführlicher sein.
--> also Statt "Methode zum Empfangen von Daten" noch dazuschreiben, wie die Methode Daten Empfängt bzw. welchen Datentyp sie empfängt.

Außerdem gibt es bei Javaeditor so ein nettes kleines Feature namens "automatisch einrücken", dessen Nutzung ich dir sehr ans Herz lege.

**Comment by MoritzGerlach** [comment]
OK, ich muss nach bessern. Das Problem ist, dass ich mich mit Javaeditor nicht auskennen. Aber wo ist der Button mit dem "automatisch einrücken".
** Ich werde es verbessern.**

**Comment by MoritzGerlach** [comment]
Warte mal. Das sind ja alles _private_ Methoden. Werden die überhaut in der JavaDoc angezeigt? 
@RubenHaag
